freebsd_instance:
  image-family: freebsd-12-1

task:
  install_script: pkg install -y cmake git m4 gawk pkgconf bash wx31-gtk3 libssh openssl libnfs neon libarchive samba411 pcre spdlog uchardet
  script: mkdir build && cd build && make -j $(getconf _NPROCESSORS_ONLN) && ./install/far2l --help
