freebsd_test_task:
    freebsd_instance:
        image_family: freebsd-14-0
    name: cirrus/FreeBSD
    install_script: pkg install -y cmake git pkgconf bash wx32-gtk3 libssh openssl libnfs neon libarchive samba416 pcre uchardet libxml2
    script: mkdir build && cd build && cmake .. && make -j $(getconf _NPROCESSORS_ONLN) && ./install/far2l --help

macos_test_task:
    macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-xcode:14.2
    name: cirrus/MacOS_M1
    install_script: brew update && brew bundle -v
    script: mkdir build && cd build && cmake -G Ninja .. && ninja -j$(getconf _NPROCESSORS_ONLN) -v
