freebsd_instance:
  image_family: freebsd-12-1

task:
  name: cirrus/FreeBSD
  install_script: pkg install -y cmake git m4 gawk pkgconf bash wx31-gtk3 libssh openssl libnfs neon libarchive samba411 pcre spdlog uchardet xerces-c3
  script: mkdir build && cd build && cmake .. && make -j $(getconf _NPROCESSORS_ONLN) && ./install/far2l --help
