#pragma once

/*
fileedit.hpp

Редактирование файла - меню
*/
/*
Copyright (c) 1996 Eugene Roshal
Copyright (c) 2000 Far Group
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. The name of the authors may not be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

class FileEditor;

enum enumEditorMenus
{
	MENU_FILE,
	MENU_EDIT,
	MENU_NAVIGATE,
	MENU_VIEW
};

enum enumFileMenu
{
	MENU_FILE_OPEN,
	MENU_FILE_SAVE,
	MENU_FILE_SAVE_AS,
	MENU_FILE_SAVE_Q,
	MENU_FILE_RECENT,
	MENU_FILE_SEPARATOR1,
	MENU_FILE_PRINT,
	MENU_FILE_PRINTER,
	MENU_FILE_SEPARATOR2,
	MENU_FILE_GO_TO_PANEL,
	MENU_FILE_EXIT,
	MENU_FILE_SEPARATOR3,
	MENU_FILE_HELP,
	MENU_FILE_PLUGINS,
	MENU_FILE_SCREEN_LIST,
	MENU_FILE_EXIT_FAR
};

enum enumEditorEditMenu
{
	MENU_EDIT_UNDO,
	MENU_EDIT_REDO,
	MENU_EDIT_SEPARATOR1,
	MENU_EDIT_SELECT_ALL,
	MENU_EDIT_SELECT_VERTICAL,
	MENU_EDIT_SEPARATOR2,
	MENU_EDIT_CUT,
	MENU_EDIT_COPY,
	MENU_EDIT_PASTE,
	MENU_EDIT_DELETE,
	MENU_EDIT_DELETE_LINE,
	MENU_EDIT_DELETE_LEFT,
	MENU_EDIT_DELETE_RIGHT,
	MENU_EDIT_DELETE_EOL,
	MENU_EDIT_SEPARATOR3,
	MENU_EDIT_FIND,
	MENU_EDIT_FIND_REPLACE,
	MENU_EDIT_FIND_NEXT,
	MENU_EDIT_FIND_PREV,
	MENU_EDIT_SEPARATOR4,
	MENU_EDIT_SHORT_FNAME,
	MENU_EDIT_FULL_FNAME,
	MENU_EDIT_LEFT_PATH,
	MENU_EDIT_RIGHT_PATH,
	MENU_EDIT_ACTIVE_PATH,
	MENU_EDIT_INACTIVE_PATH,
	MENU_EDIT_BLOCK_UNINDENT,
	MENU_EDIT_BLOCK_INDENT
};

enum enumNavigateMenu
{
	MENU_NAV_GOTO_LINE,
	MENU_NAV_TOP,
	MENU_NAV_BOTTOM,
	MENU_NAV_BEGIN_FILE,
	MENU_NAV_END_FILE,
	MENU_NAV_SEPARATOR1,
	MENU_NAV_BM_0,
	MENU_NAV_BM_1,
	MENU_NAV_BM_2,
	MENU_NAV_BM_3,
	MENU_NAV_BM_4,
	MENU_NAV_BM_5,
	MENU_NAV_BM_6,
	MENU_NAV_BM_7,
	MENU_NAV_BM_8,
	MENU_NAV_BM_9,
	MENU_NAV_SEPARATOR2,
	MENU_NAV_PIN_BM_0,
	MENU_NAV_PIN_BM_1,
	MENU_NAV_PIN_BM_2,
	MENU_NAV_PIN_BM_3,
	MENU_NAV_PIN_BM_4,
	MENU_NAV_PIN_BM_5,
	MENU_NAV_PIN_BM_6,
	MENU_NAV_PIN_BM_7,
	MENU_NAV_PIN_BM_8,
	MENU_NAV_PIN_BM_9
};

enum enumViewMenu
{
	MENU_VIEW_KEYBAR,
	MENU_VIEW_TITLEBAR,
	MENU_VIEW_MENUBAR,
	MENU_VIEW_WORDWRAP,
	MENU_VIEW_NUMBERS,
	MENU_VIEW_SPACES,
	MENU_VIEW_TABS_TO_SPACES,
	MENU_VIEW_OVERTYPE,
	MENU_VIEW_FULL_SCREEN,
	MENU_VIEW_LOCK,
	MENU_VIEW_CONSOLE,
	MENU_VIEW_SEPARATOR1,
	MENU_VIEW_TABSIZE,
	MENU_VIEW_UTF8_OEM_ANSI,
	MENU_VIEW_CODEPAGE,
	MENU_VIEW_VIEWER,
	MENU_VIEW_SEPARATOR2,
	MENU_VIEW_OPTIONS
};

void EditorShellOptions(int LastCommand, MOUSE_EVENT_RECORD *MouseEvent, FileEditor* fileEditor);

