#pragma once
#include <string>
#include <windows.h>
#include "DialogUtils.h"


class SiteConnectionEditor
{
	std::string _initial_display_name, _display_name;
	std::string _initial_protocol, _protocol, _host, _username, _password, _directory, _options;
	unsigned int _initial_port = 0, _port = 0;

	int _i_display_name = -1, _i_display_name_autogen = -1;
	int _i_dblbox = -1, _i_protocol = -1, _i_host = -1, _i_port = -1;
	int _i_username = -1, _i_password = -1;
	int _i_directory = -1, _i_protocol_options = -1;
	int _i_save = -1, _i_connect = -1, _i_cancel = -1;

	FarDialogItems _di;
	FarListWrapper _di_protocols;


	static LONG_PTR WINAPI sDlgProc(HANDLE hDlg, int Msg, int Param1, LONG_PTR Param2);
	LONG_PTR DlgProc(HANDLE hDlg, int Msg, int Param1, LONG_PTR Param2);

	void TextFromDialogControl(HANDLE dlg, int ctl, std::string &str);
	void DataFromDialog(HANDLE dlg);
	void AutogenerateDisplayName(HANDLE dlg);

public:
	SiteConnectionEditor(const std::string &display_name);


	bool Edit();

	const std::string &DisplayName() const { return _display_name; }
};
