#!/bin/bash
set -e

SRC="$1"
DST="$2"
PYTHON="$3"
CC="$4 -E -DFAR_USE_INTERNALS -DWINAPI= -DWINAPIV= -D__cdecl="

FAR2SDK="$SRC/far2l/far2sdk"
WINPORT="$SRC/WinPort"

mkdir -p "$DST/staging" "$DST/far2sdk"

echo '/** This file is autogenerated */' > "$DST/far2sdk/farcolor.h"
echo '/** This file is autogenerated */' > "$DST/far2sdk/farkeys.h"
echo '/** This file is autogenerated */' > "$DST/far2sdk/farplug-wide.h"


grep $'#define[ \t]*VK_\| KEYEVENTF_' "$WINPORT/WinCompat.h" >> "$DST/far2sdk/farkeys.h"
grep $'#define[ \t]*.*_KEY_BASE' "$FAR2SDK/farkeys.h" >> "$DST/far2sdk/farkeys.h"

grep $'#define[ \t]*FARMANAGERVERSION_' "$FAR2SDK/farplug-wide.h" >> "$DST/far2sdk/farplug-wide.h"
echo '#define CP_AUTODETECT -1' >> "$DST/far2sdk/farplug-wide.h"

function preprocess_sdk_header
{
	grep -v '#include\|#pragma' "$1" | grep -v $'WINAPI _export' | $CC - |grep -v '^#' >> "$2"
	sed -i 's/(\ \*FAR/(\*FAR/g' "$2"
	for CODE in {33..38} {40,41} {43..45} {47..90} {94..126}; do
		CHR=$(printf "\x$(printf %x $CODE)")
		sed -i "s '$CHR' $CODE g" "$2"
	done
	sed -i "s/'\\\\''/39/g" "$2"
	sed -i "s/'\\*'/42/g" "$2"
	sed -i "s/'\\.'/46/g" "$2"
	sed -i "s/'\\['/91/g" "$2"
	sed -i "s/'\\\\\\\\'/92/g" "$2"
	sed -i "s/'\\]'/93/g" "$2"
	sed -i "s/'{'/123/g" "$2"
	sed -i "s/'}'/125/g" "$2"
}

preprocess_sdk_header "$FAR2SDK/farcolor.h" "$DST/far2sdk/farcolor.h" &
preprocess_sdk_header "$FAR2SDK/farkeys.h" "$DST/far2sdk/farkeys.h" &
preprocess_sdk_header "$FAR2SDK/farplug-wide.h" "$DST/far2sdk/farplug-wide.h" &
wait


###################

if [ ! -f "$DST/python/.prepared" ]; then
	echo "Preparing python virtual env at $DST/python using $PYTHON"
	mkdir -p "$DST/python"
	$PYTHON -m venv --system-site-packages "$DST/python"
	"$DST/python/bin/python" -m pip install cffi debugpy
	echo "1" > "$DST/python/.prepared"
fi

###################

cp -f -R \
	"$SRC/python/configs/plug/far2l/"* \
	"$DST/far2sdk/farplug-wide.h" \
	"$DST/far2sdk/farkeys.h" \
	"$DST/far2sdk/farcolor.h" \
	"$DST/staging/"

"$DST/python/bin/python" "$SRC/python/src/pythongen.py" "${DST}"
