/* XPM */
static const char *const main_icon_0[] = {
/* columns rows colors chars-per-pixel */
"16 16 6 1",
"  c black",
". c blue",
"X c #808080",
"o c #C0C0C0",
"O c gray100",
"+ c None",
/* pixels */
"++++++++++++++++",
"+++         ++++",
"++ OOOOOOOoX +++",
"++ O......oX +++",
"++ O......oX +++",
"++ O......oX +++",
"++ O......oX +++",
"++ O......oX +++",
"++ ooooooooX  ++",
"+ XXXXXXXXXXOX +",
" OOOOOOOOOOOoX +",
" OoooooXXXXoXX +",
" oXXXXXXXXXXX ++",
"+            +++",
"++++++++++++++++",
"++++++++++++++++"
};

/* XPM */
static const char *const main_icon_1[] = {
/* columns rows colors chars-per-pixel */
"32 32 7 1",
"  c black",
". c navy",
"X c blue",
"o c #808080",
"O c #C0C0C0",
"+ c gray100",
"@ c None",
/* pixels */
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@                 @@@@@@",
"@@@@@@@@ OOOOOOOOOOOOOOOOo @@@@@",
"@@@@@@@ OOOOOOOOOOOOOOOOoo @@@@@",
"@@@@@@ +++++++++++++++Oooo @@@@@",
"@@@@@@ +..............Oooo @@@@@",
"@@@@@@ +.XXXXXXXXXXXXXOooo @@@@@",
"@@@@@@ +.XXXXXXXXXXXXXOooo @@@@@",
"@@@@@@ +.XXXXXXXXXXXXXOooo @@@@@",
"@@@@@@ +.XXXXXXXXXXXXXOooo @@@@@",
"@@@@@@ +.XXXXXXXXXXXXXOooo @@@@@",
"@@@@@@ +.XXXXXXXXXXXXXOooo @@@@@",
"@@@@@@ +.XXXXXXXXXXXXXOooo @@@@@",
"@@@@@@ +.XXXXXXXXXXXXXOooo @@@@@",
"@@@@@@ +++++++++++++++Oooo   @@@",
"@@@@@  +OOOOOOOOOOOOOOooo O+o @@",
"@@@@ O Ooooooooooooooooo O+oo @@",
"@@@ OO                  O+ooo @@",
"@@ ++++++++++++++++++++++Oooo @@",
"@@ +OOOOOOOOOOOOOOOOOOOOOoooo @@",
"@@ +OOOOOOOOOOOOOOOOOOOOOooo @@@",
"@@ +OOOOOOOOOOOOo      oOoo @@@@",
"@@ Ooooooooooooooooooooooo @@@@@",
"@@@                       @@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
};

/* XPM */
static const char *const main_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 7 1",
"  c black",
". c navy",
"X c blue",
"o c #808080",
"O c #C0C0C0",
"+ c gray100",
"@ c None",
/* pixels */
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@                         @@@@@@@@@@",
"@@@@@@@@@@@@ OOOOOOOOOOOOOOOOOOOOOOOOo @@@@@@@@@",
"@@@@@@@@@@@ OOOOOOOOOOOOOOOOOOOOOOOOoo @@@@@@@@@",
"@@@@@@@@@@ OOOOOOOOOOOOOOOOOOOOOOOOooo @@@@@@@@@",
"@@@@@@@@@ +++++++++++++++++++++++Ooooo @@@@@@@@@",
"@@@@@@@@@ +oooooooooooooooooooooOooooo @@@@@@@@@",
"@@@@@@@@@ +o....................+ooooo @@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@",
"@@@@@@@@@ +o.XXXXXXXXXXXXXXXXXXX+ooooo @@@@@@@@@",
"@@@@@@@@  +O+++++++++++++++++++++ooooo     @@@@@",
"@@@@@@@ O +OOOOOOOOOOOOOOOOOOOOOOoooo OO++o @@@@",
"@@@@@@ OO +OOOOOOOOOOOOOOOOOOOOOOooo OO++oo @@@@",
"@@@@@ OOO Ooooooooooooooooooooooooo OO++ooo @@@@",
"@@@@ OOOO                          OO++oooo @@@@",
"@@@ ++++++++++++++++++++++++++++++++++Ooooo @@@@",
"@@@ +++++++++++++++++++++++++++++++++Oooooo @@@@",
"@@@ ++OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoooooo @@@@",
"@@@ ++OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOoooooo @@@@",
"@@@ ++OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOooooo @@@@@",
"@@@ ++OOOOOOOOOOOOOOOOOO          oOOoooo @@@@@@",
"@@@ OOoooooooooooooooooooooooooooooooooo @@@@@@@",
"@@@ OOooooooooooooooooooooooooooooooooo @@@@@@@@",
"@@@@                                   @@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
};

const char *const *const main_icon[] = {
    main_icon_0,
    main_icon_1,
    main_icon_2,
};
const int n_main_icon = 3;
