/* XPM */
static const char *const cfg_icon_0[] = {
/* columns rows colors chars-per-pixel */
"16 16 9 1",
"  c black",
". c navy",
"X c blue",
"o c #808000",
"O c yellow",
"+ c #808080",
"@ c #C0C0C0",
"# c gray100",
"$ c None",
/* pixels */
"$$$  $$       $$",
"$$ OO  #####@+ $",
"$ $ oO #XX..@+ $",
" o $ oO+X.O.@+ $",
" oO  OO .O.X@+ $",
"$ oOOOOoO++@@+ $",
"$$ oooOOoOO +++ ",
"$ # oooOO +++++ ",
"$ #X..ooOO +++ $",
"$ #X.O. oOO   $$",
"$ #.O.X@ oOO $$$",
"$ @++@@@+ oOO $$",
"$ ++++++++ oOO $",
" #####++++  oOO ",
" @+++++++ $$ oO ",
"$        $$$$  $"
};

/* XPM */
static const char *const cfg_icon_1[] = {
/* columns rows colors chars-per-pixel */
"32 32 9 1",
"  c black",
". c navy",
"X c blue",
"o c #808000",
"O c yellow",
"+ c #808080",
"@ c #C0C0C0",
"# c gray100",
"$ c None",
/* pixels */
"$$$$$$$$$$$$$$$$            $$$$",
"$$$$$$  $$$$$$$ @@@@@@@@@@@+ $$$",
"$$$$$ OO  $$$$ ##########@++ $$$",
"$$$$$ ooOO $$$ #.........@++ $$$",
"$$$$$$ ooOO $$ #.XXXXXXXX@++ $$$",
"$$  $$$ oOO $$ #.XXXX  XX@++ $$$",
"$ oO $$ oOOO $ #.XXX O XX@++ $$$",
"$ oOO  oOOOO $ #.X  O XXX@++ $$$",
"$$ oOOOOOOO $$ #. OO XXXX@++ $$$",
"$$ ooOOOOOOO $ # OO XXXXX@++ $$$",
"$$$ ooooooOOO   OO ######@++   $",
"$$$$  oo ooOOO OO +++++++++ @#+ ",
"$$$$$$  $ ooOOO            @#++ ",
"$$$$$$$$$$ ooOOO OOOO ######@++ ",
"$$$$$     O ooOOO O  @@@@@@@+++ ",
"$$$$ @@@@@   ooOOO @@+    +@++ $",
"$$$ ######### ooOOO +++++++++ $$",
"$$$ #....... O ooOOO         $$$",
"$$$ #.XXXXX OO  ooOOO $$$$$$$$$$",
"$$$ #.XXXX OO @+ ooOOO $$$$$$$$$",
"$$$ #.XXX O  X@++ ooOOO $$$$$$$$",
"$$$ #.XX O XXX@++  ooOOO $$$$$$$",
"$$$ #.XX  XXXX@++ $ ooOOO $$$$$$",
"$$$ #.XXXXXXXX@++ $$ ooOOO $$$$$",
"$$$ ##########@++   $ ooOOO $$$$",
"$$  @+++++++++++ @#+ $ ooOOO $$$",
"$ @             @#++ $$ ooOOO $$",
" ################@++ $$$ ooO $$$",
" #@@@@@@@@@@@@@@@+++ $$$$ o $$$$",
" #@@@@@@@@+    +@++ $$$$$$ $$$$$",
" @++++++++++++++++ $$$$$$$$$$$$$",
"$                 $$$$$$$$$$$$$$"
};

/* XPM */
static const char *const cfg_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 9 1",
"  c black",
". c navy",
"X c blue",
"o c #808000",
"O c yellow",
"+ c #808080",
"@ c #C0C0C0",
"# c gray100",
"$ c None",
/* pixels */
"$$$$$$$$$$$$$$$$$$$$$$$$$                  $$$$$",
"$$$$$$$$$$$$$$$$$$$$$$$$ @@@@@@@@@@@@@@@@@+ $$$$",
"$$$$$$$$$  $$$$$$$$$$$$ @@@@@@@@@@@@@@@@@++ $$$$",
"$$$$$$$$ OO   $$$$$$$$ ################@+++ $$$$",
"$$$$$$$$ oOOOO $$$$$$$ #++++++++++++++@++++ $$$$",
"$$$$$$$$$ ooOOO $$$$$$ #+.............#++++ $$$$",
"$$$$$$$$$$ ooOOO $$$$$ #+.XXXXXXXXXXXX#++++ $$$$",
"$$$$$$$$$$$ oOOO $$$$$ #+.XXXXXXXXXXXX#++++ $$$$",
"$$$  $$$$$$ oOOO $$$$$ #+.XXXXXXX  XXX#++++ $$$$",
"$$ oO $$$$$ oOOOO $$$$ #+.XXXXXX O XXX#++++ $$$$",
"$$ ooO $$$$ oOOOO $$$$ #+.XXXXX O XXXX#++++ $$$$",
"$$$ oOO    OOOOO $$$$$ #+.XXX  O XXXXX#++++ $$$$",
"$$$ ooOOOOOOOOOOO $$$$ #+.XX OO XXXXXX#++++ $$$$",
"$$$ ooOOOOOOOOOOOO $$$ #+.X OO XXXXXXX#++++ $$$$",
"$$$$ oooOOOOoOOOOOO $$ #@  OO #########++++    $",
"$$$$$ oooooooOOOOOOO   # OOO @@@@@@@@@@+++ @##+ ",
"$$$$$$   oo ooOOOOOOO   OO  +++++++++++++ @##++ ",
"$$$$$$$$$  $ ooOOOOOOO OO                @##+++ ",
"$$$$$$$$$$$$$ ooOOOOOOO        ############@+++ ",
"$$$$$$$$$$$$$$ ooOOOOOOO OOOOOO ##########@++++ ",
"$$$$$$$$$$$$$$$ ooOOOOOOO OOO  @@+       @++++ $",
"$$$$$$$$$$$$$$$$ ooOOOOOOO O ++++++++++++++++ $$",
"$$$$$$$$$$$$$$$ O ooOOOOOOO ++++++++++++++++ $$$",
"$$$$$$$$$$$$$$$$   ooOOOOOOO                $$$$",
"$$$$$$$             ooOOOOOOO $$$$$$$$$$$$$$$$$$",
"$$$$$$ @@@@@@@@@@@@  ooOOOOOOO $$$$$$$$$$$$$$$$$",
"$$$$$ @@@@@@@@@@@@ OO ooOOOOOOO $$$$$$$$$$$$$$$$",
"$$$$ ############ OO   ooOOOOOOO $$$$$$$$$$$$$$$",
"$$$$ #++++++++++ OO @++ ooOOOOOOO $$$$$$$$$$$$$$",
"$$$$ #+........ OO .#+++ ooOOOOOOO $$$$$$$$$$$$$",
"$$$$ #+.XXXXXX O  XX#++++ ooOOOOOOO $$$$$$$$$$$$",
"$$$$ #+.XXXXX O XXXX#++++  ooOOOOOOO $$$$$$$$$$$",
"$$$$ #+.XXXX O XXXXX#++++ $ ooOOOOOOO $$$$$$$$$$",
"$$$$ #+.XXXX  XXXXXX#++++ $$ ooOOOOOOO $$$$$$$$$",
"$$$$ #+.XXXXXXXXXXXX#++++ $$$ ooOOOOOOO $$$$$$$$",
"$$$$ #+.XXXXXXXXXXXX#++++ $$$$ ooOOOOOOO $$$$$$$",
"$$$$ #+.XXXXXXXXXXXX#++++ $$$$$ ooOOOOOOO $$$$$$",
"$$$$ #+.XXXXXXXXXXXX#++++ $$$$$$ ooOOOOOOO $$$$$",
"$$$$ #@##############++++    $$$$ ooOOOOOOO $$$$",
"$$$  #@@@@@@@@@@@@@@@+++ @##+ $$$$ ooOOOOOOO $$$",
"$$ @ @+++++++++++++++++ @##++ $$$$$ ooOOOOO $$$$",
"$ @@                   @##+++ $$$$$$ ooOOO $$$$$",
" ########################@+++ $$$$$$$ ooO $$$$$$",
" #######################@++++ $$$$$$$$ o $$$$$$$",
" ##@@@@@@@@@@@@+       @++++ $$$$$$$$$$ $$$$$$$$",
" @@++++++++++++++++++++++++ $$$$$$$$$$$$$$$$$$$$",
" @@+++++++++++++++++++++++ $$$$$$$$$$$$$$$$$$$$$",
"$                         $$$$$$$$$$$$$$$$$$$$$$"
};

const char *const *const cfg_icon[] = {
    cfg_icon_0,
    cfg_icon_1,
    cfg_icon_2,
};
const int n_cfg_icon = 3;
