/* XPM */
static const char *const main_icon_0[] = {
/* columns rows colors chars-per-pixel */
"16 16 8 1",
"  c black",
". c navy",
"X c blue",
"o c yellow",
"O c #808080",
"+ c #C0C0C0",
"@ c gray100",
"# c None",
/* pixels */
"#######       ##",
"###### @@@@@+O #",
"###### @XX..+O #",
"###### @X.o.+O #",
"###### O.o.X+O #",
"###### ooOO++O #",
"##    ooooo OOO ",
"# @Oooooo OOOOO ",
"# @X..oo  OOOO #",
"# @X.o.OO     ##",
"# @.o.X+O ######",
"# +OO+++O ######",
"# OOOOOOOO #####",
" @@@@@OOOO #####",
" +OOOOOOO ######",
"#        #######"
};

/* XPM */
static const char *const main_icon_1[] = {
/* columns rows colors chars-per-pixel */
"32 32 8 1",
"  c black",
". c navy",
"X c blue",
"o c yellow",
"O c #808080",
"+ c #C0C0C0",
"@ c gray100",
"# c None",
/* pixels */
"################            ####",
"############### +++++++++++O ###",
"############## @@@@@@@@@@+OO ###",
"############## @.........+OO ###",
"############## @.XXXXXXXX+OO ###",
"############## @.XXXX  XX+OO ###",
"############## @.XXX o XX+OO ###",
"############## @.X  o XXX+OO ###",
"############## @. oo XXXX+OO ###",
"############## @ oo XXXXX+OO ###",
"##############  oo @@@@@@+OO   #",
"############# ooo OOOOOOOOO +@O ",
"############ ooo           +@OO ",
"##########  ooooooooo @@@@@@+OO ",
"#####     ooooooooo  +++++++OOO ",
"#### +++++     ooo ++O    O+OO #",
"### @@@@@@@@@ ooo OOOOOOOOOOO ##",
"### @....... oo              ###",
"### @.XXXXX oo OO ##############",
"### @.XXXX oo +OO ##############",
"### @.XXX o  X+OO ##############",
"### @.XX o XXX+OO ##############",
"### @.XX  XXXX+OO ##############",
"### @.XXXXXXXX+OO ##############",
"### @@@@@@@@@@+OO   ############",
"##  +OOOOOOOOOOO +@O ###########",
"# +             +@OO ###########",
" @@@@@@@@@@@@@@@@+OO ###########",
" @+++++++++++++++OOO ###########",
" @++++++++O    O+OO ############",
" +OOOOOOOOOOOOOOOO #############",
"#                 ##############"
};

/* XPM */
static const char *const main_icon_2[] = {
/* columns rows colors chars-per-pixel */
"48 48 8 1",
"  c black",
". c navy",
"X c blue",
"o c yellow",
"O c #808080",
"+ c #C0C0C0",
"@ c gray100",
"# c None",
/* pixels */
"#########################                  #####",
"######################## +++++++++++++++++O ####",
"####################### +++++++++++++++++OO ####",
"###################### @@@@@@@@@@@@@@@@+OOO ####",
"###################### @OOOOOOOOOOOOOO+OOOO ####",
"###################### @O.............@OOOO ####",
"###################### @O.XXXXXXXXXXXX@OOOO ####",
"###################### @O.XXXXXXXXXXXX@OOOO ####",
"###################### @O.XXXXXXX  XXX@OOOO ####",
"###################### @O.XXXXXX o XXX@OOOO ####",
"###################### @O.XXXXX o XXXX@OOOO ####",
"###################### @O.XXX  o XXXXX@OOOO ####",
"###################### @O.XX oo XXXXXX@OOOO ####",
"###################### @O.X oo XXXXXXX@OOOO ####",
"###################### @+  oo @@@@@@@@@OOOO    #",
"#####################  @ ooo ++++++++++OOO +@@O ",
"#################### +  oo  OOOOOOOOOOOOO +@@OO ",
"################### +  oo                +@@OOO ",
"################## @ ooo       @@@@@@@@@@@@+OOO ",
"##################  ooooooooooo @@@@@@@@@@+OOOO ",
"################## oooooooooo  ++O       +OOOO #",
"################  oooooooooo OOOOOOOOOOOOOOOO ##",
"############### ooooooooooo OOOOOOOOOOOOOOOO ###",
"################       ooo                  ####",
"#######               oo  ######################",
"###### ++++++++++++  oo O ######################",
"##### ++++++++++++ ooo OO ######################",
"#### @@@@@@@@@@@@ oo  OOO ######################",
"#### @OOOOOOOOOO oo +OOOO ######################",
"#### @O........ oo .@OOOO ######################",
"#### @O.XXXXXX o  XX@OOOO ######################",
"#### @O.XXXXX o XXXX@OOOO ######################",
"#### @O.XXXX o XXXXX@OOOO ######################",
"#### @O.XXXX  XXXXXX@OOOO ######################",
"#### @O.XXXXXXXXXXXX@OOOO ######################",
"#### @O.XXXXXXXXXXXX@OOOO ######################",
"#### @O.XXXXXXXXXXXX@OOOO ######################",
"#### @O.XXXXXXXXXXXX@OOOO ######################",
"#### @+@@@@@@@@@@@@@@OOOO    ###################",
"###  @+++++++++++++++OOO +@@O ##################",
"## + +OOOOOOOOOOOOOOOOO +@@OO ##################",
"# ++                   +@@OOO ##################",
" @@@@@@@@@@@@@@@@@@@@@@@@+OOO ##################",
" @@@@@@@@@@@@@@@@@@@@@@@+OOOO ##################",
" @@++++++++++++O       +OOOO ###################",
" ++OOOOOOOOOOOOOOOOOOOOOOOO ####################",
" ++OOOOOOOOOOOOOOOOOOOOOOO #####################",
"#                         ######################"
};

const char *const *const main_icon[] = {
    main_icon_0,
    main_icon_1,
    main_icon_2,
};
const int n_main_icon = 3;
