name: BSD CI

on: [push, pull_request]

jobs:
  test-freebsd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests in FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          sync: rsync
          prepare: |
            pkg install -y cmake git pkgconf bash wx32-gtk2 libssh openssl libnfs neon libarchive samba416 uchardet libxml2
          run: |
			mkdir -p _build && cmake -S . -B _build -Wno-dev && cmake --build _build --config $BUILD_TYPE -j$(getconf _NPROCESSORS_ONLN)
